// <auto-generated />
using System;
using DevContact.Domain.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevContact.Domain.Migrations
{
    [DbContext(typeof(SQLDBContext))]
    partial class SQLDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevContact.Domain.Entities.Car", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<DateTime?>("DeletedDateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModificationDateTime");

                    b.Property<string>("Ownername");

                    b.Property<string>("Registration");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("DevContact.Domain.Entities.DevContact", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<DateTime?>("DeletedDateTime");

                    b.Property<string>("Email");

                    b.Property<string>("Fullname");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModificationDateTime");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("DevContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
